# Generated by Django 4.2.7 on 2025-06-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0002_alter_story_plot_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyresponse',
            name='ai_img_path',
            field=models.CharField(blank=True, help_text='Comic image for AI reply', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storyresponse',
            name='user_img_path',
            field=models.CharField(blank=True, help_text='Comic image for user input', max_length=255, null=True),
        ),
    ]
